version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
  webapp:
    image: webapp
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
    ports:
      - 8080:8080
volumes:
  database:
